# Generated by Django 2.2.24 on 2021-06-07 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementcabinet', '0002_auto_20210607_2321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asistent',
        ),
    ]
