# Generated by Django 2.2.24 on 2021-06-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementcabinet', '0003_delete_asistent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medic',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
