# Generated by Django 2.2.24 on 2021-06-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementcabinet', '0004_auto_20210607_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('id_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=560, null=True)),
                ('notes', models.TextField(blank=True, default='', max_length=1500, null=True)),
                ('status', models.BooleanField(default=True)),
                ('college', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('graduation_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='medic',
            name='address',
            field=models.CharField(blank=True, max_length=560, null=True),
        ),
        migrations.AlterField(
            model_name='medic',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='medic',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medic',
            name='graduation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='medic',
            name='id_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medic',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medic',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='medic',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medic',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='medic',
            name='university',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
