# Generated by Django 2.2.24 on 2021-06-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementcabinet', '0008_auto_20210609_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistent',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medic',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=255, null=True),
        ),
    ]
