# Generated by Django 2.2.24 on 2021-06-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementcabinet', '0011_auto_20210609_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asistent',
        ),
        migrations.AlterField(
            model_name='medic',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medic',
            name='email',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medic',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medic',
            name='graduation_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medic',
            name='id_no',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medic',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medic',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='medic',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medic',
            name='status',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medic',
            name='university',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
