# Generated by Django 2.2.24 on 2021-06-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementcabinet', '0013_auto_20210609_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('id_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('phone_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('notes', models.TextField(blank=True, default='', max_length=1500, null=True)),
                ('status', models.BooleanField(default=True)),
                ('contact_person', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='asistent',
            name='phone_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medic',
            name='phone_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asistent',
            name='address',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='asistent',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='medic',
            name='address',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='medic',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
