# Generated by Django 2.2.24 on 2021-06-09 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementcabinet', '0016_auto_20210609_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistent',
            name='data_absolvirii',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='medic',
            name='data_absolvirii',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Programare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_si_ora', models.DateTimeField()),
                ('durata_in_minute', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True, default='', max_length=1500, null=True)),
                ('status', models.BooleanField(default=True)),
                ('asistent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementcabinet.Asistent')),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementcabinet.Medic')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementcabinet.Pacient')),
            ],
        ),
    ]
