# Generated by Django 2.2.24 on 2021-06-09 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementcabinet', '0017_auto_20210609_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durata_in_minute', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True, default='', max_length=1500, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='', max_length=1500, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar_factura', models.SmallIntegerField()),
                ('serie_factura', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('emitent', models.CharField(default='Cabinet stomatologic Smart Soft Dent', max_length=255)),
                ('cantitate', models.FloatField()),
                ('pret_unitar', models.FloatField()),
                ('data_emitere', models.DateField()),
                ('notes', models.TextField(blank=True, default='', max_length=1500, null=True)),
                ('status', models.BooleanField(default=True)),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementcabinet.Pacient')),
            ],
        ),
        migrations.CreateModel(
            name='Partener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=255)),
                ('tip_partener', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('valid_pana_la', models.DateField()),
                ('notes', models.TextField(blank=True, default='', max_length=1500, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=255)),
                ('cantitate', models.PositiveSmallIntegerField()),
                ('data_de_expirare', models.DateField()),
                ('unitate_de_masura', models.CharField(blank=True, default='buc', max_length=255, null=True)),
                ('pret', models.FloatField()),
                ('notes', models.TextField(blank=True, default='', max_length=1500, null=True)),
                ('status', models.BooleanField(default=True)),
                ('distribuitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementcabinet.Partener')),
            ],
        ),
        migrations.CreateModel(
            name='Tratament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='', max_length=1500, null=True)),
                ('status', models.BooleanField(default=True)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementcabinet.Produs')),
            ],
        ),
        migrations.CreateModel(
            name='FisaPacient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='', max_length=1500, null=True)),
                ('status', models.BooleanField(default=True)),
                ('consultatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementcabinet.Consultatie')),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementcabinet.Diagnostic')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementcabinet.Factura')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementcabinet.Pacient')),
                ('programare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementcabinet.Programare')),
                ('tratament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementcabinet.Tratament')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='produs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementcabinet.Produs'),
        ),
        migrations.AddField(
            model_name='factura',
            name='tratament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementcabinet.Tratament'),
        ),
    ]
