# Generated by Django 2.2.24 on 2021-06-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementcabinet', '0018_auto_20210609_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partener',
            name='tip_partener',
        ),
        migrations.AddField(
            model_name='partener',
            name='tip_contract',
            field=models.CharField(blank=True, default='Furnizor', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tratament',
            name='cantitate',
            field=models.FloatField(default='1'),
        ),
    ]
