# Generated by Django 2.2.24 on 2021-06-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementcabinet', '0019_auto_20210609_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='serie_factura',
            field=models.CharField(blank=True, default='SSD', max_length=20, null=True),
        ),
    ]
