# Generated by Django 2.2.24 on 2021-06-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementcabinet', '0020_auto_20210609_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistent',
            name='cnp',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='asistent',
            name='colegiu',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asistent',
            name='data_absolvirii',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asistent',
            name='imagine',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='cnp',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='medic',
            name='data_absolvirii',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medic',
            name='imagine',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='cnp',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='imagine',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='persoana_de_contact',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
