# Generated by Django 2.2.24 on 2021-06-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementcabinet', '0021_auto_20210610_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistent',
            name='specializare',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medic',
            name='specializare',
            field=models.CharField(default='', max_length=255),
        ),
    ]
