# Generated by Django 2.2.24 on 2021-06-10 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementcabinet', '0022_auto_20210610_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produs',
            old_name='pret',
            new_name='pret_unitar',
        ),
    ]
