# Generated by Django 2.2.24 on 2021-06-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementcabinet', '0023_auto_20210610_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='pacient',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='produs',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='tratament',
        ),
        migrations.RemoveField(
            model_name='fisapacient',
            name='consultatie',
        ),
        migrations.RemoveField(
            model_name='fisapacient',
            name='diagnostic',
        ),
        migrations.RemoveField(
            model_name='fisapacient',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='fisapacient',
            name='pacient',
        ),
        migrations.RemoveField(
            model_name='fisapacient',
            name='programare',
        ),
        migrations.RemoveField(
            model_name='fisapacient',
            name='tratament',
        ),
        migrations.RemoveField(
            model_name='produs',
            name='distribuitor',
        ),
        migrations.RemoveField(
            model_name='tratament',
            name='produs',
        ),
        migrations.DeleteModel(
            name='Consultatie',
        ),
        migrations.DeleteModel(
            name='Diagnostic',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='FisaPacient',
        ),
        migrations.DeleteModel(
            name='Partener',
        ),
        migrations.DeleteModel(
            name='Produs',
        ),
        migrations.DeleteModel(
            name='Tratament',
        ),
    ]
